[env]
DO_NOT_TRACK=1

[tools]
nodejs = '24.13.0'
pnpm = '10.26.0'
gitleaks = '8.28.0'
lefthook = '1.12.3'
npm = "latest"

[settings]
experimental = true
lockfile = true

[[hooks.postinstall]]
script = "lefthook install"

[[hooks.postinstall]]
script = "pnpm install"
