name: Prerelease
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup
        uses: ./.github/actions/setup
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prerelease
        run: |
          pnpm run build
          pnpm dlx pkg-pr-new publish --pnpm './packages/*'
        env:
          NEXT_PUBLIC_WHISK_API_KEY: ${{ secrets.NEXT_PUBLIC_WHISK_API_KEY }}
          NEXT_PUBLIC_WHISK_API_URL: ${{ secrets.NEXT_PUBLIC_WHISK_API_URL }}
