name: Prerelease
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup
        uses: ./.github/actions/setup
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prerelease
        run: |
          pnpm run build
          pnpm dlx pkg-pr-new publish --pnpm './packages/*'
        env:
          NEXT_PUBLIC_WHISK_API_KEY: ${{ secrets.NEXT_PUBLIC_WHISK_API_KEY }}
          NEXT_PUBLIC_WHISK_API_URL: ${{ secrets.NEXT_PUBLIC_WHISK_API_URL }}
